import type { Metadata } from "next";
import Provider from "@/Provider";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import InitUser from "@/InitUser";

export const metadata: Metadata = {
  title: "Snapcart | 10 minutes grocery Delivery App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-b from-green-50 to-white">
        <Provider>
            <StoreProvider>
                <InitUser />
               {children}
            </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
